# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.cache/wt} [current_project]
set_property parent.project_path {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/imports/res/weights.coe}}
add_files {{C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/imports/res/00.coe}}
read_mem {{C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/font5x7_cols.mem}}
read_verilog -library xil_defaultlib {
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/MatrixPages.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/imports/Desktop/Oled_Display.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/aidan.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/convert_clk6p25m.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/cursor_crosshair.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/dec_bcd_rom.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/int_sqrt32.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/labels_lut.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/linear_regression.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/mainmenu.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/menu.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/mode_approx.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/mode_plot.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/mouse_click_edge.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/mouse_io.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/plot_graph.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/poly_coef.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/poly_type.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/ryanmodule.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/userdata_module.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/vetri.v}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/new/Top_Student.v}
}
read_vhdl -library xil_defaultlib {
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/imports/Desktop/Mouse_Control.vhd}
  {C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/sources_1/imports/Desktop/Ps2Interface.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/constrs_1/imports/labs/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/vetri/Downloads/Telegram Desktop/integrated_v9.xpr/FDP/FDP.srcs/constrs_1/imports/labs/Basys3_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
